### ISSUE TITLE
thread 'main' panicked at 'wgpu error: Validation Error

### ISSUE THREAD

**Issue by lomirus** [JMS55/sandbox#45]
When I try to scale the window, it sometimes crashes:
```bash
$ RUST_BACKTRACE=1 cargo run --release
    Finished release [optimized] target(s) in 0.07s
     Running `target/release/sandbox`
thread 'main' panicked at 'wgpu error: Validation Error

Caused by:
    In a RenderPass
      note: encoder = `pixels_command_encoder`
    In a set_scissor_rect command
    Scissor Rect { x: 108, y: 10, w: 1352, h: 55 } is not contained in the render target Extent3d { width: 1440, height: 810, depth_or_array_layers: 1 }

', /home/lomirus/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.13.1/src/backend/direct.rs:2391:5
stack backtrace:
   0: rust_begin_unwind
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/panicking.rs:65:14
   2: core::ops::function::Fn::call
   3: <wgpu::RenderPass as core::ops::drop::Drop>::drop
   4: sandbox::ui::UI::render
   5: pixels::Pixels::render_with
   6: sandbox::main::{{closure}}.14851
   7: winit::platform_impl::platform::x11::EventLoop<T>::run
   8: winit::platform_impl::platform::EventLoop<T>::run
   9: winit::event_loop::EventLoop<T>::run
  10: sandbox::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

System Info:
```
GPU: NVIDIA 01:00.0 NVIDIA Corporation TU117M
DE: GNOME 43.2 
WM: Mutter
OS: Manjaro Linux x86_64
Windows System: X11
```

**Comment by JMS55** [comment]
Thanks for the bug report! Unfortunately I am not currently working on Sandbox. I'll look into this when I come back to working on the project.
